move partition labels into config

diff --git a/tmp/install/profile/lvm_luks/storage b/tmp/install/profile/lvm_luks/storage
--- a/tmp/install/profile/lvm_luks/storage
+++ b/tmp/install/profile/lvm_luks/storage
@@ -1,3 +1,9 @@
+#!/bin/bash
+#
+# This runs very early. Before preinstall.
+# Its job is to make sure that the partitions named in the profile config exist,
+# are formatted and labeled, but not mounted yet.
+
 [[ -v installbase ]] || source /tmp/install/common.sh
 
 get_disksize() {
@@ -20,7 +26,7 @@ get_only_child() {
 print_parted_commands() {
   local disksize efizsize
   disksize=$(get_disksize)
-  efisize=$(get_config .defaultsize.efisys)
+  efisize=$(get_profile_config .partition.efi.defaultsize)
   efisize=${efisize:-2044}
   local pvrootsize=$(( disksize - efisize - 32 ))
   local pos=4
@@ -44,8 +50,13 @@ gen_new_lukskey() {
 }
 
 create_partitions() {
-  local disk part pvroot luksroot lukskey rootsize homesize
-  lukskey=$(get_config .lukskey)
+  local disk part pvroot luksroot lukskey rootsize homesize label_home label_root label_efi
+  label_home=$(get_label home) || return
+  label_root=$(get_label root) || return
+  label_efi=$(get_label efi) || return
+  [[ $label_home = luks-* ]] || return $(error "invalid label: home")
+  [[ $label_root = luks-* ]] || return $(error "invalid label: root")
+  lukskey=$(get_profile_config .lukskey)
   if [[ $lukskey ]]; then
     echo -n "$lukskey" > $installbase/lukskey
   else
@@ -57,22 +68,22 @@ create_partitions() {
     done
   fi
   disk=$(get_disk) || return $(error "get_disk")
-  parted --script --align optimal $disk -- $(print_parted_commands) || return $(error "parted")
-  mkfs.vfat -n EFISYS -F 32 $(by_partlabel EFISYS) || return $(error "mkfs vfat")
+  parted --script --align optimal $disk -- $(print_parted_commands) || return 
+  mkfs.vfat -n $label_efi -F 32 $(by_partlabel EFISYS) || return
   pvroot=$(by_partlabel pvroot)
   chmod 600 $installbase/lukskey
-  cryptsetup luksFormat --force-password --batch-mode $pvroot $installbase/lukskey || return $(error "crypt format")
-  cryptsetup luksOpen --batch-mode --key-file=$installbase/lukskey $pvroot luks || return $(error "crypt open")
-  cryptsetup config $pvroot --label pvroot || return $(error "crypt label")
-  luksroot=$(get_only_child $pvroot) || return $(error "find luksroot")
-  pvcreate $luksroot || return $(error "pvcreate")
-  vgcreate luks $luksroot || return $(error "vgcreate")
-  rootsize=$(get_config .defaultsize.root)
-  homesize=$(get_config .defaultsize.home)
-  lvcreate -L ${rootsize:-8192}M -n root luks || return $(error "lvcreate root")
-  lvcreate -L ${homesize:-2048}M -n home luks || return $(error "lvcreate home")
-  mkfs.ext4 -q -L luks-root /dev/mapper/luks-root <<< y || return $(error "ext4 root")
-  mkfs.ext4 -q -L luks-home /dev/mapper/luks-home <<< y || return $(error "ext4 home")
+  cryptsetup luksFormat --force-password --batch-mode $pvroot $installbase/lukskey || return
+  cryptsetup luksOpen --batch-mode --key-file=$installbase/lukskey $pvroot luks || return
+  cryptsetup config $pvroot --label pvroot || return
+  luksroot=$(get_only_child $pvroot) || return
+  pvcreate $luksroot || return
+  vgcreate luks $luksroot || return
+  rootsize=$(get_profile_config .partition.root.defaultsize)
+  homesize=$(get_profile_config .partition.home.defaultsize)
+  lvcreate -L ${rootsize:-8192}M -n ${label_root#luks-} luks || return
+  lvcreate -L ${homesize:-2048}M -n ${label_home#luks-} luks || return
+  mkfs.ext4 -q -L $label_root /dev/mapper/$label_root <<< y || return
+  mkfs.ext4 -q -L $label_home /dev/mapper/$label_home <<< y || return
 }
 
 get_existing_lukskey() {
@@ -80,7 +91,7 @@ get_existing_lukskey() {
   pvroot=$(blkid --label pvroot 2> /dev/null) || return 1
   echo "Found pvroot: $pvroot"
   if has_modifier "noask"; then
-    REPLY=$(get_config .lukskey)
+    REPLY=$(get_profile_config .lukskey)
     if [[ -z $REPLY ]]; then
       return $(error "in noask mode, lukskey must be configured")
     fi
@@ -98,15 +109,20 @@ get_existing_lukskey() {
 
 unlock_pvroot() {
   [[ -f $installbase/lukskey ]] || return 1
-  local pvroot luks_root efisys
-  efisys=$(blkid --label EFISYS) || return $(error "no such label: EFISYS")
-  pvroot=$(blkid --label pvroot 2> /dev/null) || return 1
+  local pvroot luks_root efisys label_home label_root label_efi
+  label_home=$(get_label home) || return
+  label_root=$(get_label root) || return
+  label_efi=$(get_label efi) || return
+  [[ $label_home = luks-* ]] || return $(error "invalid label: home")
+  [[ $label_root = luks-* ]] || return $(error "invalid label: root")
+  efisys=$(blkid --label $label_efi) || return
+  pvroot=$(blkid --label pvroot 2> /dev/null) || return
   cryptsetup luksOpen -q --disable-external-tokens --key-file $installbase/lukskey $pvroot luks || return
   vgchange -ay
-  luksroot=$(blkid --label luks-root) || return $(error "no such label: luks-root")
-  blkid --label luks-home || return $(error "no such label: luks-home")
-  mkfs.ext4 -q -L luks-root $luksroot <<< y || return $(error "mkfs luks-root")
-  mkfs.vfat -n EFISYS -F 32 $efisys || return $(error "mkfs efisys")
+  luksroot=$(blkid --label $label_root) || return
+  blkid --label $label_home || return
+  mkfs.ext4 -q -L $label_root $luksroot <<< y || return
+  mkfs.vfat -n $label_efi -F 32 $efisys || return
 }
 
 prepare_partitions() {
@@ -131,4 +147,8 @@ prepare_partitions() {
     done
   fi
   create_partitions
+}
+
+return 2> /dev/null || {
+  prepare_partitions
 }
